<img src = "img/images.png" style="height:80px;">
<div style="text-align:center;">
    
# Normalización

<img src ="img/Python-Logo.jpg" style="height:222px;">

    Marzo 25, 2026

</div>

### _Esteban Sáncez_

In [1]:
from sklearn import preprocessing
import numpy as np

In [2]:
# carga de datos
x_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(x_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [3]:
# Limpieza de datos 
normalizer = preprocessing.MinMaxScaler()
x_train_norm = normalizer.fit_transform(x_train)

In [4]:
# Resultados
print(x_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [5]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
x_train_2 = np.copy(x_train)

# Crea un objeto "fitted_normalizer" llamando al método "fit"
f = normalizer.fit(x_train)

# Aplica el objeto sobre los datos "x_train_2" para obtener "x_train_norm_2"
x_train_norm_2 = f.transform(x_train)

# Comprueba si "x_train_norm" y "x_train_norm_2" son iguales
print(np.array_equiv(x_train_norm, x_train_norm_2))

True


In [6]:
# Normalizar un nuevo conjunto de datos de test

x_test = np.array([[1., -3., 2.],
                    [3., 0., 0.],
                    [0., 4., -1.]])

print(x_test)

[[ 1. -3.  2.]
 [ 3.  0.  0.]
 [ 0.  4. -1.]]


In [7]:
x_test_norm = normalizer.transform(x_test)
print(x_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


[Repositorio en GitHub](https://github.com/EstebanSan140106/Machine-E-Learning-2.git)